{{- if .Values.cmdb }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nameSpace }}
  labels:
      chart: {{ template "chart-app.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
{{- end }}
