{{- if .Values.cmdb }}
{{- if .Values.vault }}
{{- $fullName := include "chart-app.fullname" . -}}
{{- $appName := include "chart-app.name" . -}}
apiVersion: spacecontroller.seizadi.github.com/v1alpha1

kind: Space
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ $appName }}
    chart: {{ template "chart-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  secretName: {{ $fullName }}-secrets
  path: {{ .Values.vault.path }}
  secrets:
    {{- range $secret := .Values.secrets }}
      {{ $secret.key }}:
    {{- end }}
{{- end }}
{{- end }}
