apiVersion: v1
kind: Pod
metadata:
  name: contacts-app-migration
  namespace: contacts
  labels:
    app: contacts-app-migration
spec:
  restartPolicy: Never
  initContainers:
    - name: init-container1
      image: infobloxcto/contacts-server:latest
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: "/atlas-migrations"
          name: migrations
      command:
        - "cp"
        - "-r"
        - "/db/migrations"
        - "/atlas-migrations"
  containers:
  - name: migration
    env:
    - name: CONFIG_FILE
      value: defaults
    image: infoblox/migrate:latest
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /atlas-migrations
        name: migrations
    command:
      - /migrate
    args:
      - "--verbose"
      - "--source"
      - "file:///atlas-migrations/migrations"
      - "--database.address"
      - "postgres.contacts:5432"
      - "--database.name"
      - "atlas_contacts_app"
      - "--database.user"
      - "postgres"
      - "--database.password"
      - "postgres"
      - up
      # to get to a particular level append following
      #- "2"
  volumes:
    - name: migrations
      emptyDir: {}
---
