# ROLE ASSIGNMENTS
apiVersion: authz.infoblox.com/v1
kind: RoleAssignment
metadata:
  name: contacts-all-users
  namespace: contacts
  labels:
    authz-namespace: authz
subjectgroups:
  - all-users
  - infoblox-readonly
roles:
  - contacts-read-only
resourcegroups:
  - all-resources
---
apiVersion: authz.infoblox.com/v1
kind: RoleAssignment
metadata:
  name: contacts-admin
  namespace: contacts
  labels:
    authz-namespace: authz
subjectgroups:
  - administrators
  - infoblox-admin
  - infoblox-provision
  - infoblox-cicd
roles:
  - contacts-read-write
resourcegroups:
  - all-resources
---
# ROLES
apiVersion: authz.infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-only
  namespace: contacts
  labels:
    authz-namespace: authz
permissions:
  - contacts-read
---
apiVersion: authz.infoblox.com/v1
kind: Role
metadata:
  name: contacts-read-write
  namespace: contacts
  labels:
    authz-namespace: authz
permissions:
  - contacts-read
  - contacts-write
---
# PERMISSIONS
apiVersion: authz.infoblox.com/v1
kind: Permission
metadata:
  name: contacts-read
  namespace: contacts
  labels:
    authz-namespace: authz
endpoints:
  - Contacts.List
  - Contacts.Get
---
apiVersion: authz.infoblox.com/v1
kind: Permission
metadata:
  name: contacts-write
  namespace: contacts
  labels:
    authz-namespace: authz
endpoints:
  - Contacts.Create
  - Contacts.Update
  - Contacts.Delete
  - Contacts.SendSMS
---
# FEATURES
apiVersion: authz.infoblox.com/v1
kind: Feature
metadata:
  name: contacts-feature
  namespace: contacts
  labels:
    authz-namespace: authz
endpoints:
  - Contacts.List
  - Contacts.Get
  - Contacts.Create
  - Contacts.Update
  - Contacts.Delete
  - Contacts.SendSMS