metadata:
  id: cmdb-app
server:
  address: 0.0.0.0:9090
gateway:
  address: 0.0.0.0:8080
  endpoint: /cmdb
  swaggerFile: ./www/contacts.swagger.json
  swaggerUI: ./www/swagger-ui-dist/
database:
#  address: postgres.contacts:5432
  address: localhost:5432
  name: cmdb
  user: postgres
  password: postgres
  ssl: disable
atlas.authz:
  enable: false
  address : themis.authz:5555
internal:
  address: 0.0.0.0:8081
  health: /healthz
  readiness: /ready
logging:
  level: debug